'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property idCliente As Integer
    Public Property nombre As String
    Public Property DPI As String
    Public Property telefono As Nullable(Of Integer)
    Public Property correo As String

    Public Overridable Property Servicios As ICollection(Of Servicio) = New HashSet(Of Servicio)

End Class
