'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Servicio
    Public Property idServicio As Integer
    Public Property idCliente As Integer
    Public Property idUsuario As Integer
    Public Property fechaIngreso As String
    Public Property fechaEntrega As String
    Public Property tipo As String
    Public Property marca As String
    Public Property modelo As String
    Public Property descripcion As String
    Public Property falla As String
    Public Property repuesto As String
    Public Property informe As String
    Public Property costo As Integer
    Public Property estado As String

    Public Overridable Property Cliente As Cliente
    Public Overridable Property Usuario As Usuario

End Class
